- menu_name: "Destacado"

- name: "Ubicación"
  url: "/ubicacion/"
  class: "services-contact"
  title: "Ubicación"

- name: "Calendario escolar"
  url: "http://www.educa.jcyl.es/es/informacion/calendario-escolar-2015-2016"
  class: "rss-link"
  title: "Calendario escolar 2015-2016"

- name: "Intranet"
  url: "https://podio.com/intranetiessanandrescom/intranet-2015-2016"
  class: "sitemap-link"
  title: "Acceso a la Intranet"
